//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.ServiceRef.Billing.SAPConnServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputOutputDTO", Namespace="http://schemas.datacontract.org/2004/07/Misi.SAP.Connector.Object", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Misi.ServiceRef.Billing.SAPConnServ.SoldToPartiesDTO))]
    public partial class InputOutputDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoldToPartiesDTO", Namespace="http://schemas.datacontract.org/2004/07/Misi.SAP.Connector.Object", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SoldToPartiesDTO : Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misi.ServiceRef.Billing.SAPConnServ.SoldToPartyDTO[] ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misi.ServiceRef.Billing.SAPConnServ.SoldToPartyDTO[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoldToPartyDTO", Namespace="http://schemas.datacontract.org/2004/07/Misi.SAP.Connector.Object")]
    [System.SerializableAttribute()]
    public partial class SoldToPartyDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KUNNRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOEVMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAME1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VTWEGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KUNNR {
            get {
                return this.KUNNRField;
            }
            set {
                if ((object.ReferenceEquals(this.KUNNRField, value) != true)) {
                    this.KUNNRField = value;
                    this.RaisePropertyChanged("KUNNR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOEVM {
            get {
                return this.LOEVMField;
            }
            set {
                if ((object.ReferenceEquals(this.LOEVMField, value) != true)) {
                    this.LOEVMField = value;
                    this.RaisePropertyChanged("LOEVM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME1 {
            get {
                return this.NAME1Field;
            }
            set {
                if ((object.ReferenceEquals(this.NAME1Field, value) != true)) {
                    this.NAME1Field = value;
                    this.RaisePropertyChanged("NAME1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPART {
            get {
                return this.SPARTField;
            }
            set {
                if ((object.ReferenceEquals(this.SPARTField, value) != true)) {
                    this.SPARTField = value;
                    this.RaisePropertyChanged("SPART");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VTWEG {
            get {
                return this.VTWEGField;
            }
            set {
                if ((object.ReferenceEquals(this.VTWEGField, value) != true)) {
                    this.VTWEGField = value;
                    this.RaisePropertyChanged("VTWEG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAPConnServ.ISAPConnector")]
    public interface ISAPConnector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAPConnector/GetBillingItems", ReplyAction="http://tempuri.org/ISAPConnector/GetBillingItemsResponse")]
        Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO GetBillingItems(string user, string soldToParty, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAPConnector/GetBillingItems", ReplyAction="http://tempuri.org/ISAPConnector/GetBillingItemsResponse")]
        System.Threading.Tasks.Task<Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO> GetBillingItemsAsync(string user, string soldToParty, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAPConnector/GetSoldToParties", ReplyAction="http://tempuri.org/ISAPConnector/GetSoldToPartiesResponse")]
        Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO GetSoldToParties(string user, string orgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAPConnector/GetSoldToParties", ReplyAction="http://tempuri.org/ISAPConnector/GetSoldToPartiesResponse")]
        System.Threading.Tasks.Task<Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO> GetSoldToPartiesAsync(string user, string orgNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAPConnectorChannel : Misi.ServiceRef.Billing.SAPConnServ.ISAPConnector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAPConnectorClient : System.ServiceModel.ClientBase<Misi.ServiceRef.Billing.SAPConnServ.ISAPConnector>, Misi.ServiceRef.Billing.SAPConnServ.ISAPConnector {
        
        public SAPConnectorClient() {
        }
        
        public SAPConnectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAPConnectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAPConnectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAPConnectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO GetBillingItems(string user, string soldToParty, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetBillingItems(user, soldToParty, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO> GetBillingItemsAsync(string user, string soldToParty, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetBillingItemsAsync(user, soldToParty, startDate, endDate);
        }
        
        public Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO GetSoldToParties(string user, string orgNumber) {
            return base.Channel.GetSoldToParties(user, orgNumber);
        }
        
        public System.Threading.Tasks.Task<Misi.ServiceRef.Billing.SAPConnServ.InputOutputDTO> GetSoldToPartiesAsync(string user, string orgNumber) {
            return base.Channel.GetSoldToPartiesAsync(user, orgNumber);
        }
    }
}
