// <auto-generated />
namespace Misi.DAL.Billing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class DalBilling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DalBilling));
        
        string IMigrationMetadata.Id
        {
            get { return "201506150828535_DalBilling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
