//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.Service.Billing.HelpdeskConnectorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tickets", Namespace="http://schemas.datacontract.org/2004/07/Misi.Helpdesk.Connector.Service")]
    [System.SerializableAttribute()]
    public partial class Tickets : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Misi.Service.Billing.HelpdeskConnectorService.TicketVo[] CollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Misi.Service.Billing.HelpdeskConnectorService.TicketVo[] Collection {
            get {
                return this.CollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionField, value) != true)) {
                    this.CollectionField = value;
                    this.RaisePropertyChanged("Collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketVo", Namespace="http://schemas.datacontract.org/2004/07/Misi.Helpdesk.Connector.Object")]
    [System.SerializableAttribute()]
    public partial class TicketVo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyWBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CounterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptCodeEscalateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptEscalateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DetailCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DeviceTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EscalateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EscalateSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExistingDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromDeptCodeEscalateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromDeptEscalateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromEscalateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromEscalateSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdxReqProblemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IsSmupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MTicketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrjIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrjNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProblemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProblemHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReopenLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportHelpdeskByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevenueTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubRevenueTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrgencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WBSNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WorkingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearPurchaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetNo {
            get {
                return this.AssetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetNoField, value) != true)) {
                    this.AssetNoField = value;
                    this.RaisePropertyChanged("AssetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attach {
            get {
                return this.AttachField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachField, value) != true)) {
                    this.AttachField = value;
                    this.RaisePropertyChanged("Attach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyWBS {
            get {
                return this.CompanyWBSField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyWBSField, value) != true)) {
                    this.CompanyWBSField = value;
                    this.RaisePropertyChanged("CompanyWBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Counter {
            get {
                return this.CounterField;
            }
            set {
                if ((this.CounterField.Equals(value) != true)) {
                    this.CounterField = value;
                    this.RaisePropertyChanged("Counter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptCodeEscalate {
            get {
                return this.DeptCodeEscalateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptCodeEscalateField, value) != true)) {
                    this.DeptCodeEscalateField = value;
                    this.RaisePropertyChanged("DeptCodeEscalate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptEscalate {
            get {
                return this.DeptEscalateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptEscalateField, value) != true)) {
                    this.DeptEscalateField = value;
                    this.RaisePropertyChanged("DeptEscalate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescStatus {
            get {
                return this.DescStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DescStatusField, value) != true)) {
                    this.DescStatusField = value;
                    this.RaisePropertyChanged("DescStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailCategory {
            get {
                return this.DetailCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailCategoryField, value) != true)) {
                    this.DetailCategoryField = value;
                    this.RaisePropertyChanged("DetailCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DetailCategoryId {
            get {
                return this.DetailCategoryIdField;
            }
            set {
                if ((this.DetailCategoryIdField.Equals(value) != true)) {
                    this.DetailCategoryIdField = value;
                    this.RaisePropertyChanged("DetailCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceType {
            get {
                return this.DeviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceTypeField, value) != true)) {
                    this.DeviceTypeField = value;
                    this.RaisePropertyChanged("DeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeviceTypeId {
            get {
                return this.DeviceTypeIdField;
            }
            set {
                if ((this.DeviceTypeIdField.Equals(value) != true)) {
                    this.DeviceTypeIdField = value;
                    this.RaisePropertyChanged("DeviceTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDateAct {
            get {
                return this.EndDateActField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateActField, value) != true)) {
                    this.EndDateActField = value;
                    this.RaisePropertyChanged("EndDateAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTimeAct {
            get {
                return this.EndTimeActField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeActField, value) != true)) {
                    this.EndTimeActField = value;
                    this.RaisePropertyChanged("EndTimeAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Escalate {
            get {
                return this.EscalateField;
            }
            set {
                if ((object.ReferenceEquals(this.EscalateField, value) != true)) {
                    this.EscalateField = value;
                    this.RaisePropertyChanged("Escalate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EscalateSn {
            get {
                return this.EscalateSnField;
            }
            set {
                if ((object.ReferenceEquals(this.EscalateSnField, value) != true)) {
                    this.EscalateSnField = value;
                    this.RaisePropertyChanged("EscalateSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExistingDevice {
            get {
                return this.ExistingDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExistingDeviceField, value) != true)) {
                    this.ExistingDeviceField = value;
                    this.RaisePropertyChanged("ExistingDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ext {
            get {
                return this.ExtField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtField, value) != true)) {
                    this.ExtField = value;
                    this.RaisePropertyChanged("Ext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDeptCodeEscalate {
            get {
                return this.FromDeptCodeEscalateField;
            }
            set {
                if ((object.ReferenceEquals(this.FromDeptCodeEscalateField, value) != true)) {
                    this.FromDeptCodeEscalateField = value;
                    this.RaisePropertyChanged("FromDeptCodeEscalate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDeptEscalate {
            get {
                return this.FromDeptEscalateField;
            }
            set {
                if ((object.ReferenceEquals(this.FromDeptEscalateField, value) != true)) {
                    this.FromDeptEscalateField = value;
                    this.RaisePropertyChanged("FromDeptEscalate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEscalate {
            get {
                return this.FromEscalateField;
            }
            set {
                if ((object.ReferenceEquals(this.FromEscalateField, value) != true)) {
                    this.FromEscalateField = value;
                    this.RaisePropertyChanged("FromEscalate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEscalateSn {
            get {
                return this.FromEscalateSnField;
            }
            set {
                if ((object.ReferenceEquals(this.FromEscalateSnField, value) != true)) {
                    this.FromEscalateSnField = value;
                    this.RaisePropertyChanged("FromEscalateSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Idx {
            get {
                return this.IdxField;
            }
            set {
                if ((this.IdxField.Equals(value) != true)) {
                    this.IdxField = value;
                    this.RaisePropertyChanged("Idx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdxReqProblem {
            get {
                return this.IdxReqProblemField;
            }
            set {
                if ((this.IdxReqProblemField.Equals(value) != true)) {
                    this.IdxReqProblemField = value;
                    this.RaisePropertyChanged("IdxReqProblem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impact {
            get {
                return this.ImpactField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpactField, value) != true)) {
                    this.ImpactField = value;
                    this.RaisePropertyChanged("Impact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IsSmup {
            get {
                return this.IsSmupField;
            }
            set {
                if ((this.IsSmupField.Equals(value) != true)) {
                    this.IsSmupField = value;
                    this.RaisePropertyChanged("IsSmup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastIp {
            get {
                return this.LastIpField;
            }
            set {
                if ((object.ReferenceEquals(this.LastIpField, value) != true)) {
                    this.LastIpField = value;
                    this.RaisePropertyChanged("LastIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdateField, value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUser {
            get {
                return this.LastUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUserField, value) != true)) {
                    this.LastUserField = value;
                    this.RaisePropertyChanged("LastUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MTicketId {
            get {
                return this.MTicketIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MTicketIdField, value) != true)) {
                    this.MTicketIdField = value;
                    this.RaisePropertyChanged("MTicketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrjId {
            get {
                return this.PrjIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PrjIdField, value) != true)) {
                    this.PrjIdField = value;
                    this.RaisePropertyChanged("PrjId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrjName {
            get {
                return this.PrjNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrjNameField, value) != true)) {
                    this.PrjNameField = value;
                    this.RaisePropertyChanged("PrjName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Problem {
            get {
                return this.ProblemField;
            }
            set {
                if ((object.ReferenceEquals(this.ProblemField, value) != true)) {
                    this.ProblemField = value;
                    this.RaisePropertyChanged("Problem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProblemHeader {
            get {
                return this.ProblemHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProblemHeaderField, value) != true)) {
                    this.ProblemHeaderField = value;
                    this.RaisePropertyChanged("ProblemHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo {
            get {
                return this.ReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNoField, value) != true)) {
                    this.ReferenceNoField = value;
                    this.RaisePropertyChanged("ReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReopenLevel {
            get {
                return this.ReopenLevelField;
            }
            set {
                if ((this.ReopenLevelField.Equals(value) != true)) {
                    this.ReopenLevelField = value;
                    this.RaisePropertyChanged("ReopenLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportBy {
            get {
                return this.ReportByField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportByField, value) != true)) {
                    this.ReportByField = value;
                    this.RaisePropertyChanged("ReportBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportDate {
            get {
                return this.ReportDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportDateField, value) != true)) {
                    this.ReportDateField = value;
                    this.RaisePropertyChanged("ReportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportHelpdeskBy {
            get {
                return this.ReportHelpdeskByField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportHelpdeskByField, value) != true)) {
                    this.ReportHelpdeskByField = value;
                    this.RaisePropertyChanged("ReportHelpdeskBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportTime {
            get {
                return this.ReportTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTimeField, value) != true)) {
                    this.ReportTimeField = value;
                    this.RaisePropertyChanged("ReportTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportVia {
            get {
                return this.ReportViaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportViaField, value) != true)) {
                    this.ReportViaField = value;
                    this.RaisePropertyChanged("ReportVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportedTime {
            get {
                return this.ReportedTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportedTimeField, value) != true)) {
                    this.ReportedTimeField = value;
                    this.RaisePropertyChanged("ReportedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolution {
            get {
                return this.ResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolutionField, value) != true)) {
                    this.ResolutionField = value;
                    this.RaisePropertyChanged("Resolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevenueType {
            get {
                return this.RevenueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueTypeField, value) != true)) {
                    this.RevenueTypeField = value;
                    this.RaisePropertyChanged("RevenueType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sla {
            get {
                return this.SlaField;
            }
            set {
                if ((object.ReferenceEquals(this.SlaField, value) != true)) {
                    this.SlaField = value;
                    this.RaisePropertyChanged("Sla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusTicket {
            get {
                return this.StatusTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusTicketField, value) != true)) {
                    this.StatusTicketField = value;
                    this.RaisePropertyChanged("StatusTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubRevenueType {
            get {
                return this.SubRevenueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubRevenueTypeField, value) != true)) {
                    this.SubRevenueTypeField = value;
                    this.RaisePropertyChanged("SubRevenueType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketId {
            get {
                return this.TicketIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketIdField, value) != true)) {
                    this.TicketIdField = value;
                    this.RaisePropertyChanged("TicketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeDetail {
            get {
                return this.TimeDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeDetailField, value) != true)) {
                    this.TimeDetailField = value;
                    this.RaisePropertyChanged("TimeDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urgency {
            get {
                return this.UrgencyField;
            }
            set {
                if ((object.ReferenceEquals(this.UrgencyField, value) != true)) {
                    this.UrgencyField = value;
                    this.RaisePropertyChanged("Urgency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAccess {
            get {
                return this.UserAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAccessField, value) != true)) {
                    this.UserAccessField = value;
                    this.RaisePropertyChanged("UserAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WBSNo {
            get {
                return this.WBSNoField;
            }
            set {
                if ((object.ReferenceEquals(this.WBSNoField, value) != true)) {
                    this.WBSNoField = value;
                    this.RaisePropertyChanged("WBSNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty {
            get {
                return this.WarrantyField;
            }
            set {
                if ((object.ReferenceEquals(this.WarrantyField, value) != true)) {
                    this.WarrantyField = value;
                    this.RaisePropertyChanged("Warranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WorkingTime {
            get {
                return this.WorkingTimeField;
            }
            set {
                if ((this.WorkingTimeField.Equals(value) != true)) {
                    this.WorkingTimeField = value;
                    this.RaisePropertyChanged("WorkingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YearPurchase {
            get {
                return this.YearPurchaseField;
            }
            set {
                if ((object.ReferenceEquals(this.YearPurchaseField, value) != true)) {
                    this.YearPurchaseField = value;
                    this.RaisePropertyChanged("YearPurchase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelpdeskConnectorService.IHelpdeskServ")]
    public interface IHelpdeskServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/SelectAllTickets", ReplyAction="http://tempuri.org/IHelpdeskServ/SelectAllTicketsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IHelpdeskServ/SelectAllTicketsFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Misi.Service.Billing.HelpdeskConnectorService.Tickets SelectAllTickets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/SelectAllTickets", ReplyAction="http://tempuri.org/IHelpdeskServ/SelectAllTicketsResponse")]
        System.Threading.Tasks.Task<Misi.Service.Billing.HelpdeskConnectorService.Tickets> SelectAllTicketsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/SelectLimitedTickets", ReplyAction="http://tempuri.org/IHelpdeskServ/SelectLimitedTicketsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IHelpdeskServ/SelectLimitedTicketsFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Misi.Service.Billing.HelpdeskConnectorService.Tickets SelectLimitedTickets(int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/SelectLimitedTickets", ReplyAction="http://tempuri.org/IHelpdeskServ/SelectLimitedTicketsResponse")]
        System.Threading.Tasks.Task<Misi.Service.Billing.HelpdeskConnectorService.Tickets> SelectLimitedTicketsAsync(int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/SelectTicket", ReplyAction="http://tempuri.org/IHelpdeskServ/SelectTicketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IHelpdeskServ/SelectTicketFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        Misi.Service.Billing.HelpdeskConnectorService.TicketVo SelectTicket(string ticketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/SelectTicket", ReplyAction="http://tempuri.org/IHelpdeskServ/SelectTicketResponse")]
        System.Threading.Tasks.Task<Misi.Service.Billing.HelpdeskConnectorService.TicketVo> SelectTicketAsync(string ticketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/TotalTickets", ReplyAction="http://tempuri.org/IHelpdeskServ/TotalTicketsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IHelpdeskServ/TotalTicketsFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        int TotalTickets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelpdeskServ/TotalTickets", ReplyAction="http://tempuri.org/IHelpdeskServ/TotalTicketsResponse")]
        System.Threading.Tasks.Task<int> TotalTicketsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelpdeskServChannel : Misi.Service.Billing.HelpdeskConnectorService.IHelpdeskServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelpdeskServClient : System.ServiceModel.ClientBase<Misi.Service.Billing.HelpdeskConnectorService.IHelpdeskServ>, Misi.Service.Billing.HelpdeskConnectorService.IHelpdeskServ {
        
        public HelpdeskServClient() {
        }
        
        public HelpdeskServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelpdeskServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelpdeskServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelpdeskServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Misi.Service.Billing.HelpdeskConnectorService.Tickets SelectAllTickets() {
            return base.Channel.SelectAllTickets();
        }
        
        public System.Threading.Tasks.Task<Misi.Service.Billing.HelpdeskConnectorService.Tickets> SelectAllTicketsAsync() {
            return base.Channel.SelectAllTicketsAsync();
        }
        
        public Misi.Service.Billing.HelpdeskConnectorService.Tickets SelectLimitedTickets(int offset, int limit) {
            return base.Channel.SelectLimitedTickets(offset, limit);
        }
        
        public System.Threading.Tasks.Task<Misi.Service.Billing.HelpdeskConnectorService.Tickets> SelectLimitedTicketsAsync(int offset, int limit) {
            return base.Channel.SelectLimitedTicketsAsync(offset, limit);
        }
        
        public Misi.Service.Billing.HelpdeskConnectorService.TicketVo SelectTicket(string ticketId) {
            return base.Channel.SelectTicket(ticketId);
        }
        
        public System.Threading.Tasks.Task<Misi.Service.Billing.HelpdeskConnectorService.TicketVo> SelectTicketAsync(string ticketId) {
            return base.Channel.SelectTicketAsync(ticketId);
        }
        
        public int TotalTickets() {
            return base.Channel.TotalTickets();
        }
        
        public System.Threading.Tasks.Task<int> TotalTicketsAsync() {
            return base.Channel.TotalTicketsAsync();
        }
    }
}
