//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BillingReportingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BillingReportingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.BillingReportingResource", typeof(BillingReportingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendix.
        /// </summary>
        public static string Appendix {
            get {
                return ResourceManager.GetString("Appendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Doc. Number.
        /// </summary>
        public static string BillingDocNumber {
            get {
                return ResourceManager.GetString("BillingDocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Item.
        /// </summary>
        public static string BillingItem {
            get {
                return ResourceManager.GetString("BillingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request for Billing.
        /// </summary>
        public static string BillingServiceRequestTitle {
            get {
                return ResourceManager.GetString("BillingServiceRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Item.
        /// </summary>
        public static string ContractItem {
            get {
                return ResourceManager.GetString("ContractItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No..
        /// </summary>
        public static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        public static string Deduction {
            get {
                return ResourceManager.GetString("Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string Holder {
            get {
                return ResourceManager.GetString("Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR Date.
        /// </summary>
        public static string IdrDate {
            get {
                return ResourceManager.GetString("IdrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR No..
        /// </summary>
        public static string IdrNo {
            get {
                return ResourceManager.GetString("IdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect External Data.
        /// </summary>
        public static string IncorrectExternalData {
            get {
                return ResourceManager.GetString("IncorrectExternalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendix.
        /// </summary>
        public static string IsAppendixSelected {
            get {
                return ResourceManager.GetString("IsAppendixSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice (Detail).
        /// </summary>
        public static string IsInvoiceDetailSelected {
            get {
                return ResourceManager.GetString("IsInvoiceDetailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice (Total).
        /// </summary>
        public static string IsInvoiceSelected {
            get {
                return ResourceManager.GetString("IsInvoiceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Date From.
        /// </summary>
        public static string IssuedDateFrom {
            get {
                return ResourceManager.GetString("IssuedDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string IssuedDateTo {
            get {
                return ResourceManager.GetString("IssuedDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material No..
        /// </summary>
        public static string MaterialNo {
            get {
                return ResourceManager.GetString("MaterialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MST Invoice.
        /// </summary>
        public static string MSTInvoice {
            get {
                return ResourceManager.GetString("MSTInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org. Unit.
        /// </summary>
        public static string OrgUnit {
            get {
                return ResourceManager.GetString("OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Mat.Code.
        /// </summary>
        public static string OriginMatCode {
            get {
                return ResourceManager.GetString("OriginMatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU Code.
        /// </summary>
        public static string OuCode {
            get {
                return ResourceManager.GetString("OuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pers. Area.
        /// </summary>
        public static string PersArea {
            get {
                return ResourceManager.GetString("PersArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Device.
        /// </summary>
        public static string ReturnDevice {
            get {
                return ResourceManager.GetString("ReturnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Number.
        /// </summary>
        public static string SalaryNumber {
            get {
                return ResourceManager.GetString("SalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string ScenarioCheckList {
            get {
                return ResourceManager.GetString("ScenarioCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Area.
        /// </summary>
        public static string SubArea {
            get {
                return ResourceManager.GetString("SubArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination.
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
