//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CSSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.CSSResource", typeof(CSSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-default  btn btn-sm btn-white.
        /// </summary>
        public static string EndFormButton {
            get {
                return ResourceManager.GetString("EndFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-lg-offset-3 col-lg-8.
        /// </summary>
        public static string EndFormButtonDiv {
            get {
                return ResourceManager.GetString("EndFormButtonDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form-control.
        /// </summary>
        public static string FormControl {
            get {
                return ResourceManager.GetString("FormControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-8.
        /// </summary>
        public static string FormControlDiv {
            get {
                return ResourceManager.GetString("FormControlDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form-control global.
        /// </summary>
        public static string FormControlGlobal {
            get {
                return ResourceManager.GetString("FormControlGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-3 control-label label-tooltip.
        /// </summary>
        public static string FormLabel {
            get {
                return ResourceManager.GetString("FormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-1 control-label label-tooltip.
        /// </summary>
        public static string FormLabelPair {
            get {
                return ResourceManager.GetString("FormLabelPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-12.
        /// </summary>
        public static string FullPage {
            get {
                return ResourceManager.GetString("FullPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-4.
        /// </summary>
        public static string HalfFormControlDiv {
            get {
                return ResourceManager.GetString("HalfFormControlDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-6.
        /// </summary>
        public static string HalfPage {
            get {
                return ResourceManager.GetString("HalfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-6 col-md-offset-6 help-text.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-plus.
        /// </summary>
        public static string IconAdd {
            get {
                return ResourceManager.GetString("IconAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-close.
        /// </summary>
        public static string IconCancel {
            get {
                return ResourceManager.GetString("IconCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-search.
        /// </summary>
        public static string IconDisplay {
            get {
                return ResourceManager.GetString("IconDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-file-excel-o.
        /// </summary>
        public static string IconExportToExcel {
            get {
                return ResourceManager.GetString("IconExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-check-square-o.
        /// </summary>
        public static string IconFinish {
            get {
                return ResourceManager.GetString("IconFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-chevron-right.
        /// </summary>
        public static string IconNext {
            get {
                return ResourceManager.GetString("IconNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-print.
        /// </summary>
        public static string IconPrint {
            get {
                return ResourceManager.GetString("IconPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-info-circle.
        /// </summary>
        public static string IconRoutingInformation {
            get {
                return ResourceManager.GetString("IconRoutingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-table.
        /// </summary>
        public static string IconRoutingTable {
            get {
                return ResourceManager.GetString("IconRoutingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-play.
        /// </summary>
        public static string IconRun {
            get {
                return ResourceManager.GetString("IconRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-save.
        /// </summary>
        public static string IconSave {
            get {
                return ResourceManager.GetString("IconSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-tasks.
        /// </summary>
        public static string IconScenarioAttribute {
            get {
                return ResourceManager.GetString("IconScenarioAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-search.
        /// </summary>
        public static string IconSearch {
            get {
                return ResourceManager.GetString("IconSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process-icon-fa fa-check-square-o.
        /// </summary>
        public static string IconSubmit {
            get {
                return ResourceManager.GetString("IconSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-3.
        /// </summary>
        public static string OneFourthPage {
            get {
                return ResourceManager.GetString("OneFourthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-4.
        /// </summary>
        public static string OneThirdPage {
            get {
                return ResourceManager.GetString("OneThirdPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-2.
        /// </summary>
        public static string PairControlDiv {
            get {
                return ResourceManager.GetString("PairControlDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-6 mg-t-5.
        /// </summary>
        public static string SecondaryControlDiv {
            get {
                return ResourceManager.GetString("SecondaryControlDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row table-responsive table-resposive-custom.
        /// </summary>
        public static string TableResponsiveDiv {
            get {
                return ResourceManager.GetString("TableResponsiveDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textarea-autosize form-control global.
        /// </summary>
        public static string TextAreaControl {
            get {
                return ResourceManager.GetString("TextAreaControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col-md-8.
        /// </summary>
        public static string TwoThirdPage {
            get {
                return ResourceManager.GetString("TwoThirdPage", resourceCulture);
            }
        }
    }
}
