//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terdapat beberapa field yang tidak valid.
        /// </summary>
        public static string FormFieldNotValid {
            get {
                return ResourceManager.GetString("FormFieldNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terjadi Error yang belum diketahui. Mohon hubungi Administrator..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR !! - Cannot Retrieve Object from Web Service.
        /// </summary>
        public static string WCFCannotGetObject {
            get {
                return ResourceManager.GetString("WCFCannotGetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;bootstrap&quot;&gt;
        ///    &lt;div class=&quot;alert alert-danger&quot;&gt;
        ///        &lt;button data-dismiss=&quot;alert&quot; class=&quot;close&quot; type=&quot;button&quot;&gt;x&lt;/button&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;
        ///                Error: Cannot Retrieve Object from SAP
        ///            &lt;/li&gt;
        ///        &lt;/ul&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string WCFCannotGetObjectHTML {
            get {
                return ResourceManager.GetString("WCFCannotGetObjectHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR !! - Object Sent to Web Service cannot be Saved.
        /// </summary>
        public static string WCFCannotSave {
            get {
                return ResourceManager.GetString("WCFCannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR !! - Object Sent to Web Service cannot be Submitted to SAP.
        /// </summary>
        public static string WCFCannotSubmitToSAP {
            get {
                return ResourceManager.GetString("WCFCannotSubmitToSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR !! - Object Sent to Web Service cannot be Updated.
        /// </summary>
        public static string WCFCannotUpdate {
            get {
                return ResourceManager.GetString("WCFCannotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR !! - Object Retrieved by Web Service is null.
        /// </summary>
        public static string WCFNullObject {
            get {
                return ResourceManager.GetString("WCFNullObject", resourceCulture);
            }
        }
    }
}
