//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProformaInvoiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProformaInvoiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ProformaInvoiceResource", typeof(ProformaInvoiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional parts.
        /// </summary>
        public static string Additionalparts {
            get {
                return ResourceManager.GetString("Additionalparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned by the System (Internal).
        /// </summary>
        public static string AssignedbytheSystem {
            get {
                return ResourceManager.GetString("AssignedbytheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Block.
        /// </summary>
        public static string BillingBlock {
            get {
                return ResourceManager.GetString("BillingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Blocked.
        /// </summary>
        public static string BillingBlocked {
            get {
                return ResourceManager.GetString("BillingBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Blocked.
        /// </summary>
        public static string BillingBlocked1 {
            get {
                return ResourceManager.GetString("BillingBlocked1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing by Debit Memo.
        /// </summary>
        public static string BillingbyDebitMemo {
            get {
                return ResourceManager.GetString("BillingbyDebitMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Date From.
        /// </summary>
        public static string BillingDateFrom {
            get {
                return ResourceManager.GetString("BillingDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string BillingDateTo {
            get {
                return ResourceManager.GetString("BillingDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Doc Number.
        /// </summary>
        public static string BillingDocNumber {
            get {
                return ResourceManager.GetString("BillingDocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1970000000.
        /// </summary>
        public static string BillingdocNumber1 {
            get {
                return ResourceManager.GetString("BillingdocNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1960000000.
        /// </summary>
        public static string BillingdocNumber2 {
            get {
                return ResourceManager.GetString("BillingdocNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1950000000.
        /// </summary>
        public static string BillingdocNumber3 {
            get {
                return ResourceManager.GetString("BillingdocNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1940000000.
        /// </summary>
        public static string BillingdocNumber4 {
            get {
                return ResourceManager.GetString("BillingdocNumber4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Docs Criteria.
        /// </summary>
        public static string BillingDocsCriteria {
            get {
                return ResourceManager.GetString("BillingDocsCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Proforma Invoice from Document Number.
        /// </summary>
        public static string BillingDocumentCreateNewPopupTitle {
            get {
                return ResourceManager.GetString("BillingDocumentCreateNewPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display - Billing Document.
        /// </summary>
        public static string BillingDocumentDisplayPopupTitle {
            get {
                return ResourceManager.GetString("BillingDocumentDisplayPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run - Billing Document.
        /// </summary>
        public static string BillingDocumentRunPopupTitle {
            get {
                return ResourceManager.GetString("BillingDocumentRunPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Error Log.
        /// </summary>
        public static string BillingErrorLog {
            get {
                return ResourceManager.GetString("BillingErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Item.
        /// </summary>
        public static string BillingItem {
            get {
                return ResourceManager.GetString("BillingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Document No..
        /// </summary>
        public static string BillingNo {
            get {
                return ResourceManager.GetString("BillingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Run.
        /// </summary>
        public static string BillingRun {
            get {
                return ResourceManager.GetString("BillingRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Type.
        /// </summary>
        public static string BillingType {
            get {
                return ResourceManager.GetString("BillingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MST Proforma Invoice (ZF9).
        /// </summary>
        public static string BillingTypeMSTProformaInvoice {
            get {
                return ResourceManager.GetString("BillingTypeMSTProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor better.
        /// </summary>
        public static string Competitorbetter {
            get {
                return ResourceManager.GetString("Competitorbetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion of Contract.
        /// </summary>
        public static string CompletionOfContract {
            get {
                return ResourceManager.GetString("CompletionOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion of Contract.
        /// </summary>
        public static string CompletionofContract1 {
            get {
                return ResourceManager.GetString("CompletionofContract1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have Updated Changes first before Submitting to SAP.
        /// </summary>
        public static string ConfirmSubmitToSAP {
            get {
                return ResourceManager.GetString("ConfirmSubmitToSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Item.
        /// </summary>
        public static string ContractItem {
            get {
                return ResourceManager.GetString("ContractItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        public static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Admin.
        /// </summary>
        public static string CreatedbyList {
            get {
                return ResourceManager.GetString("CreatedbyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time.
        /// </summary>
        public static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Incorrect External Data.
        /// </summary>
        public static string CreateIncorrectExternalData {
            get {
                return ResourceManager.GetString("CreateIncorrectExternalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create On.
        /// </summary>
        public static string CreateOn {
            get {
                return ResourceManager.GetString("CreateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current number of rows.
        /// </summary>
        public static string CurrentNumberOfRows {
            get {
                return ResourceManager.GetString("CurrentNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cust.to receive replacement.
        /// </summary>
        public static string Custtoreceivereplacement {
            get {
                return ResourceManager.GetString("Custtoreceivereplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        public static string Deduction {
            get {
                return ResourceManager.GetString("Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date too late.
        /// </summary>
        public static string Deliverydatetoolate {
            get {
                return ResourceManager.GetString("Deliverydatetoolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayInvoice {
            get {
                return ResourceManager.GetString("DisplayInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Proforma Invoice.
        /// </summary>
        public static string DisplayProformaInvoice {
            get {
                return ResourceManager.GetString("DisplayProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Held.
        /// </summary>
        public static string DocumentHeld {
            get {
                return ResourceManager.GetString("DocumentHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Print.
        /// </summary>
        public static string DontPrint {
            get {
                return ResourceManager.GetString("DontPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Input.
        /// </summary>
        public static string DoubleInput {
            get {
                return ResourceManager.GetString("DoubleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Rejection.
        /// </summary>
        public static string EquipmentRejection {
            get {
                return ResourceManager.GetString("EquipmentRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Rejection.
        /// </summary>
        public static string EquipmentRejection1 {
            get {
                return ResourceManager.GetString("EquipmentRejection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Replacement.
        /// </summary>
        public static string EquipmentReplacement {
            get {
                return ResourceManager.GetString("EquipmentReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        public static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess Hours.
        /// </summary>
        public static string ExcessHours {
            get {
                return ResourceManager.GetString("ExcessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header - Proforma Invoice.
        /// </summary>
        public static string HeaderProformaInvoice {
            get {
                return ResourceManager.GetString("HeaderProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string HolderName {
            get {
                return ResourceManager.GetString("HolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR Date.
        /// </summary>
        public static string IdrDate {
            get {
                return ResourceManager.GetString("IdrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR No..
        /// </summary>
        public static string IdrNo {
            get {
                return ResourceManager.GetString("IdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly press REFRESH button on the bottom-left of table below..
        /// </summary>
        public static string InfoRefreshIfLargeData {
            get {
                return ResourceManager.GetString("InfoRefreshIfLargeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Billing Document.
        /// </summary>
        public static string IsActiveDocumentSelected {
            get {
                return ResourceManager.GetString("IsActiveDocumentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Billing Document.
        /// </summary>
        public static string IsBlockedDocumentSelected {
            get {
                return ResourceManager.GetString("IsBlockedDocumentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Final Version?.
        /// </summary>
        public static string IsFinal {
            get {
                return ResourceManager.GetString("IsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save as draft?.
        /// </summary>
        public static string IsSavedAsDraft {
            get {
                return ResourceManager.GetString("IsSavedAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string IsSelected {
            get {
                return ResourceManager.GetString("IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No.
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Sales.
        /// </summary>
        public static string LostSales {
            get {
                return ResourceManager.GetString("LostSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harap isi field di bawah ini untuk transaksi berikut:
        ///
        /// Create New                      :   -  Billing Date From/ To                          
        ///                                                    -  Sold-To Party                                                                                                            
        ///Run &amp; Display Invoice   :   - Billing Date From/ To 
        ///                                                    - Sold-To Party
        ///                                                    - Billing Run.
        /// </summary>
        public static string MainInformationHeader {
            get {
                return ResourceManager.GetString("MainInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Proforma Invoice.
        /// </summary>
        public static string MainInvoice {
            get {
                return ResourceManager.GetString("MainInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Proforma Invoice.
        /// </summary>
        public static string MainProformaInvoice {
            get {
                return ResourceManager.GetString("MainProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material No..
        /// </summary>
        public static string MaterialNo {
            get {
                return ResourceManager.GetString("MaterialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MST Proforma Invoice (ZF9)
        ///.
        /// </summary>
        public static string MSTProformaInvoice {
            get {
                return ResourceManager.GetString("MSTProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Proforma Invoice.
        /// </summary>
        public static string NewProformaInvoice {
            get {
                return ResourceManager.GetString("NewProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org. Unit.
        /// </summary>
        public static string OrgUnit {
            get {
                return ResourceManager.GetString("OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Mat. Code.
        /// </summary>
        public static string OriginMatCode {
            get {
                return ResourceManager.GetString("OriginMatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU Code.
        /// </summary>
        public static string OUCode {
            get {
                return ResourceManager.GetString("OUCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pers. Area.
        /// </summary>
        public static string PersArea {
            get {
                return ResourceManager.GetString("PersArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select ....
        /// </summary>
        public static string PleaseSelectReasonForRejection {
            get {
                return ResourceManager.GetString("PleaseSelectReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor quality.
        /// </summary>
        public static string Poorquality {
            get {
                return ResourceManager.GetString("Poorquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Specification.
        /// </summary>
        public static string ProductSpecification {
            get {
                return ResourceManager.GetString("ProductSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proforma Invoice Header.
        /// </summary>
        public static string ProformaInvoiceHeader {
            get {
                return ResourceManager.GetString("ProformaInvoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proforma Invoice Item.
        /// </summary>
        public static string ProformaInvoiceItem {
            get {
                return ResourceManager.GetString("ProformaInvoiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTTU service rejection.
        /// </summary>
        public static string PTTUservicerejection {
            get {
                return ResourceManager.GetString("PTTUservicerejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Rejection.
        /// </summary>
        public static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject in progress.
        /// </summary>
        public static string Rejectinprogress {
            get {
                return ResourceManager.GetString("Rejectinprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair and Maintenance.
        /// </summary>
        public static string RepairAndMaintenance {
            get {
                return ResourceManager.GetString("RepairAndMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement IT Device.
        /// </summary>
        public static string ReplacementITDevice {
            get {
                return ResourceManager.GetString("ReplacementITDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement parts.
        /// </summary>
        public static string Replacementparts {
            get {
                return ResourceManager.GetString("Replacementparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned IT Device.
        /// </summary>
        public static string ReturnedITDevice {
            get {
                return ResourceManager.GetString("ReturnedITDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke User Application.
        /// </summary>
        public static string RevokeUserApplication {
            get {
                return ResourceManager.GetString("RevokeUserApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunInvoice {
            get {
                return ResourceManager.GetString("RunInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Proforma Invoice.
        /// </summary>
        public static string RunProformaInvoice {
            get {
                return ResourceManager.GetString("RunProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Number.
        /// </summary>
        public static string SalaryNumber {
            get {
                return ResourceManager.GetString("SalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurray!! You have saved this Billing Run to Database successfully!!.
        /// </summary>
        public static string SaveAsDraftSuccessMessage {
            get {
                return ResourceManager.GetString("SaveAsDraftSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Document.
        /// </summary>
        public static string SdDocument {
            get {
                return ResourceManager.GetString("SdDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Document Line Item.
        /// </summary>
        public static string SDDocumentLineItem {
            get {
                return ResourceManager.GetString("SDDocumentLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Document.
        /// </summary>
        public static string SelectedDocument {
            get {
                return ResourceManager.GetString("SelectedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNorIDNumber.
        /// </summary>
        public static string SNorIDNumber {
            get {
                return ResourceManager.GetString("SNorIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold-To Party.
        /// </summary>
        public static string SoldToParty {
            get {
                return ResourceManager.GetString("SoldToParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold-To Party.
        /// </summary>
        public static string SoldToPartyFrom {
            get {
                return ResourceManager.GetString("SoldToPartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string SoldToPartyTo {
            get {
                return ResourceManager.GetString("SoldToPartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSB Service Rejection.
        /// </summary>
        public static string SSBServiceRejection {
            get {
                return ResourceManager.GetString("SSBServiceRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizaton.
        /// </summary>
        public static string Standardizaton {
            get {
                return ResourceManager.GetString("Standardizaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF400324: Team Foundation services are not available from server win2k8r2tfs.tmt.co.id..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical information (for administrator):.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote name could not be resolved: &apos;win2k8r2tfs.tmt.co.id&apos; Retry.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Area.
        /// </summary>
        public static string SubArea {
            get {
                return ResourceManager.GetString("SubArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit to SAP.
        /// </summary>
        public static string SubmitToSAP {
            get {
                return ResourceManager.GetString("SubmitToSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurray!! You have submited Billing Run to SAP successfully!!.
        /// </summary>
        public static string SubmitToSAPSucessMessage {
            get {
                return ResourceManager.GetString("SubmitToSAPSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table - Proforma Invoice.
        /// </summary>
        public static string TableProformaInvoice {
            get {
                return ResourceManager.GetString("TableProformaInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Reason.
        /// </summary>
        public static string TechnicalReason {
            get {
                return ResourceManager.GetString("TechnicalReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of payment.
        /// </summary>
        public static string Termofpayment {
            get {
                return ResourceManager.GetString("Termofpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too expensive.
        /// </summary>
        public static string Tooexpensive {
            get {
                return ResourceManager.GetString("Tooexpensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is being block.
        /// </summary>
        public static string Transactionisbeingblock {
            get {
                return ResourceManager.GetString("Transactionisbeingblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is being checked.
        /// </summary>
        public static string Transactionisbeingchecked {
            get {
                return ResourceManager.GetString("Transactionisbeingchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction to be deal.
        /// </summary>
        public static string Transactiontobedeal {
            get {
                return ResourceManager.GetString("Transactiontobedeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreasonable request.
        /// </summary>
        public static string Unreasonablerequest {
            get {
                return ResourceManager.GetString("Unreasonablerequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurray!! You have updated this Billing Run to Database successfully!!.
        /// </summary>
        public static string UpdateChangeSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateChangeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade IT Device.
        /// </summary>
        public static string UpgradeITDevice {
            get {
                return ResourceManager.GetString("UpgradeITDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZProgram Do Not Use.
        /// </summary>
        public static string ZProgramDoNotUse {
            get {
                return ResourceManager.GetString("ZProgramDoNotUse", resourceCulture);
            }
        }
    }
}
