//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoutingTableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoutingTableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.RoutingTableResources", typeof(RoutingTableResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Tolong lengkapi atribut 
        ///sesuai skenario Broken
        ///yang berkaitan
        ///2. Lengkapi Backup Equipment Number jika dibutuhkan.
        /// </summary>
        public static string BrokenInstruction1 {
            get {
                return ResourceManager.GetString("BrokenInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no IDR Web
        ///2. Mengisi no Quotation
        ///3. Memasukan Holder 
        ///    Name &amp; SN dari 
        ///    customer
        ///4. Mengisi no SO Contract.
        /// </summary>
        public static string NewContractExtLineInstruction1 {
            get {
                return ResourceManager.GetString("NewContractExtLineInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Membuat Extention Line
        ///di CUCM/ CIME
        ///2. Mengisi no Extention
        ///Line.
        /// </summary>
        public static string NewContractExtLineInstruction2 {
            get {
                return ResourceManager.GetString("NewContractExtLineInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no IDR Web
        ///2. Mengisi no Quotation
        ///3. Mengisi Device Request
        ///4. Memasukan Holder 
        ///     Name &amp; SN dari 
        ///     customer.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction1 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Equipment
        ///2. Mengisi no S/N.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction2 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melakukan reservasi 
        ///unit : holder name, mengisi lokasi, IDR no, Sold-To Party, mengubah status 
        ///Equipment menjadi 
        ///Reserved di SAP.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction3 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Asset
        ///Real dari SAP
        ///2. Mengisi no CIP dari SAP.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction4 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no notification
        ///dari SAP 
        ///2. melakukan
        ///instalasi Device
        ///3. Mengisi no Ext Line.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction5 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no SO Contract 
        ///2. Mengisi no SO Delivery.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction6 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Delivery 
        ///Order (DO) dari SAP
        ///2. Melakukan deliver unit
        ///tsb.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction7 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melakukan transfer asset
        ///dan menjalankan 
        ///depresiasinya.
        /// </summary>
        public static string NewContractIpPhoneExtLineInstruction8 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneExtLineInstruction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no IDR Web
        ///2. Mengisi no Quotation
        ///3. Mengisi Device Request
        ///4. Memasukan Holder 
        ///     Name &amp; SN dari 
        ///     customer
        ///5. Mengisi no Ext Line.
        /// </summary>
        public static string NewContractIpPhoneInstruction1 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Equipment
        ///2. Mengisi no S/N.
        /// </summary>
        public static string NewContractIpPhoneInstruction2 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melakukan reservasi 
        ///unit : mengisi holder name, lokasi, IDR no,Sold-To Party, dan mengubah status equipment menjadi 
        ///Reserved di SAP.
        /// </summary>
        public static string NewContractIpPhoneInstruction3 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Asset
        ///Real dari SAP
        ///2. Mengisi no CIP dari SAP.
        /// </summary>
        public static string NewContractIpPhoneInstruction4 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengisi no notification
        ///dari SAP dan melakukan
        ///instalasi Device.
        /// </summary>
        public static string NewContractIpPhoneInstruction5 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no SO Contract 
        ///2. Mengisi no SO Delivery.
        /// </summary>
        public static string NewContractIpPhoneInstruction6 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Delivery 
        ///Order (DO) dari SAP
        ///2. Melakukan deliver unit
        ///tsb.
        /// </summary>
        public static string NewContractIpPhoneInstruction7 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melakukan transfer asset
        ///dan menjalankan 
        ///depresiasinya.
        /// </summary>
        public static string NewContractIpPhoneInstruction8 {
            get {
                return ResourceManager.GetString("NewContractIpPhoneInstruction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no IDR Web
        ///2. Mengisi no Quotation
        ///3. Mengisi Device Request
        ///4. Memasukan Holder 
        ///     Name &amp; SN dari 
        ///     customer.
        /// </summary>
        public static string NewContractLDPInstruction1 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Equipment
        ///2. Mengisi no S/N.
        /// </summary>
        public static string NewContractLDPInstruction2 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melakukan reservasi 
        ///unit : mengisi holder name, lokasi, IDR no,Sold-To Party, dan mengubah status equipment menjadi 
        ///&quot;Reserved&quot; di SAP.
        /// </summary>
        public static string NewContractLDPInstruction3 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Asset
        ///Real dari SAP
        ///2. Mengisi no CIP dari SAP.
        /// </summary>
        public static string NewContractLDPInstruction4 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengisi no notification
        ///dari SAP dan melakukan
        ///instalasi Device.
        /// </summary>
        public static string NewContractLDPInstruction5 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no SO Contract 
        ///2. Mengisi no SO Delivery.
        /// </summary>
        public static string NewContractLDPInstruction6 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no Delivery 
        ///Order (DO) dari SAP
        ///2. Melakukan deliver unit
        ///tsb.
        /// </summary>
        public static string NewContractLDPInstruction7 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melakukan transfer asset
        ///dan menjalankan 
        ///depresiasinya.
        /// </summary>
        public static string NewContractLDPInstruction8 {
            get {
                return ResourceManager.GetString("NewContractLDPInstruction8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Mengisi no IDR Web
        ///2. Mengisi no Quotation
        ///3. Mengisi no SO Contract
        ///4. Memasukan Holder 
        ///     Name &amp; SN dari 
        ///     customer.
        /// </summary>
        public static string NewContractSoftwareInstruction1 {
            get {
                return ResourceManager.GetString("NewContractSoftwareInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memenuhi service dan mengisi service 
        ///delivery date.
        /// </summary>
        public static string NewContractSoftwareInstruction2 {
            get {
                return ResourceManager.GetString("NewContractSoftwareInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewInstruction1 {
            get {
                return ResourceManager.GetString("NewInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewInstruction2 {
            get {
                return ResourceManager.GetString("NewInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ketik response.
        /// </summary>
        public static string PlaceholderRespond {
            get {
                return ResourceManager.GetString("PlaceholderRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong lengkapi informasi  
        ///return device.
        /// </summary>
        public static string ReturnDeviceInstruction1 {
            get {
                return ResourceManager.GetString("ReturnDeviceInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong stop charges 
        ///servicenya.
        /// </summary>
        public static string ReturnDeviceInstruction2 {
            get {
                return ResourceManager.GetString("ReturnDeviceInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Instruction 1
        ///2. Instruction 2.
        /// </summary>
        public static string ScenarioNewInstruction1 {
            get {
                return ResourceManager.GetString("ScenarioNewInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong lengkapi  informasi request  terminasi.
        /// </summary>
        public static string TerminationInstruction1 {
            get {
                return ResourceManager.GetString("TerminationInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong stop charges 
        ///servicenya.
        /// </summary>
        public static string TerminationInstruction2 {
            get {
                return ResourceManager.GetString("TerminationInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong lengkapi bagian request info.
        /// </summary>
        public static string TransferAssetHolderInstruction1 {
            get {
                return ResourceManager.GetString("TransferAssetHolderInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong untuk di-return
        ///unitnya.
        /// </summary>
        public static string TransferAssetHolderInstruction2 {
            get {
                return ResourceManager.GetString("TransferAssetHolderInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Tolong stop charging
        ///2. Tolong open charging
        ///3. Tolong create 
        ///     SO Delivery.
        /// </summary>
        public static string TransferAssetHolderInstruction3 {
            get {
                return ResourceManager.GetString("TransferAssetHolderInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong di-deliver unitnya.
        /// </summary>
        public static string TransferAssetHolderInstruction4 {
            get {
                return ResourceManager.GetString("TransferAssetHolderInstruction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong lengkapi bagian request info.
        /// </summary>
        public static string TransferAssetLocationInstruction1 {
            get {
                return ResourceManager.GetString("TransferAssetLocationInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolong transfer location.
        /// </summary>
        public static string TransferAssetLocationInstruction2 {
            get {
                return ResourceManager.GetString("TransferAssetLocationInstruction2", resourceCulture);
            }
        }
    }
}
