//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScenarioTerminationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioTerminationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ScenarioTerminationResource", typeof(ScenarioTerminationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Access.
        /// </summary>
        public static string AdAccess {
            get {
                return ResourceManager.GetString("AdAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges (Gross).
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End.
        /// </summary>
        public static string ContractEnd {
            get {
                return ResourceManager.GetString("ContractEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start.
        /// </summary>
        public static string ContractStart {
            get {
                return ResourceManager.GetString("ContractStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS ID.
        /// </summary>
        public static string DbsId {
            get {
                return ResourceManager.GetString("DbsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS Service.
        /// </summary>
        public static string DbsService {
            get {
                return ResourceManager.GetString("DbsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Scenario.
        /// </summary>
        public static string DetailScenario {
            get {
                return ResourceManager.GetString("DetailScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ID.
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Service.
        /// </summary>
        public static string EmailService {
            get {
                return ResourceManager.GetString("EmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.Number.
        /// </summary>
        public static string ExtensionNumber {
            get {
                return ResourceManager.GetString("ExtensionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extention.
        /// </summary>
        public static string Extention {
            get {
                return ResourceManager.GetString("Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpdesk.
        /// </summary>
        public static string Helpdesk {
            get {
                return ResourceManager.GetString("Helpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideColumn.
        /// </summary>
        public static string HIdeColumn {
            get {
                return ResourceManager.GetString("HIdeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Name.
        /// </summary>
        public static string HolderName {
            get {
                return ResourceManager.GetString("HolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet ID.
        /// </summary>
        public static string InternetId {
            get {
                return ResourceManager.GetString("InternetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        public static string ItemCategory {
            get {
                return ResourceManager.GetString("ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN ID.
        /// </summary>
        public static string LanId {
            get {
                return ResourceManager.GetString("LanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Description.
        /// </summary>
        public static string MaterialDescription {
            get {
                return ResourceManager.GetString("MaterialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Pricing.
        /// </summary>
        public static string MaterialPricing {
            get {
                return ResourceManager.GetString("MaterialPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Number.
        /// </summary>
        public static string PoNumber {
            get {
                return ResourceManager.GetString("PoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Group.
        /// </summary>
        public static string PriceGroup {
            get {
                return ResourceManager.GetString("PriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Rejection.
        /// </summary>
        public static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        public static string RequestedBy {
            get {
                return ResourceManager.GetString("RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request memo pertama.
        /// </summary>
        public static string RequestMemo1 {
            get {
                return ResourceManager.GetString("RequestMemo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        public static string SalaryNumber {
            get {
                return ResourceManager.GetString("SalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Admin.
        /// </summary>
        public static string SalesAdmin {
            get {
                return ResourceManager.GetString("SalesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Type.
        /// </summary>
        public static string ScenarioType {
            get {
                return ResourceManager.GetString("ScenarioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-00002.
        /// </summary>
        public static string Serviceid1 {
            get {
                return ResourceManager.GetString("Serviceid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowN Column.
        /// </summary>
        public static string ShownColumn {
            get {
                return ResourceManager.GetString("ShownColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Qty.
        /// </summary>
        public static string TargetQty {
            get {
                return ResourceManager.GetString("TargetQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination.
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBS Element.
        /// </summary>
        public static string WbsElement {
            get {
                return ResourceManager.GetString("WbsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
