//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScenarioNewContractResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioNewContractResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ScenarioNewContractResource", typeof(ScenarioNewContractResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akses AD.
        /// </summary>
        public static string AksesAd {
            get {
                return ResourceManager.GetString("AksesAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Number.
        /// </summary>
        public static string AssetNumber {
            get {
                return ResourceManager.GetString("AssetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        public static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIP Number.
        /// </summary>
        public static string CipNumber {
            get {
                return ResourceManager.GetString("CipNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Line Number.
        /// </summary>
        public static string ContractLineNumber {
            get {
                return ResourceManager.GetString("ContractLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomScenario.
        /// </summary>
        public static string CustomScenario {
            get {
                return ResourceManager.GetString("CustomScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS ID.
        /// </summary>
        public static string DbsId {
            get {
                return ResourceManager.GetString("DbsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order To User.
        /// </summary>
        public static string DeliveryOrderToUser {
            get {
                return ResourceManager.GetString("DeliveryOrderToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Exchange.
        /// </summary>
        public static string EmailExchange {
            get {
                return ResourceManager.GetString("EmailExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Maintenance.
        /// </summary>
        public static string EmailMaintenance {
            get {
                return ResourceManager.GetString("EmailMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extention Line Number.
        /// </summary>
        public static string ExtentionLineNumber {
            get {
                return ResourceManager.GetString("ExtentionLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.Line.
        /// </summary>
        public static string ExtLine {
            get {
                return ResourceManager.GetString("ExtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR Web.
        /// </summary>
        public static string IdrWeb {
            get {
                return ResourceManager.GetString("IdrWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Phone.
        /// </summary>
        public static string IpPhone {
            get {
                return ResourceManager.GetString("IpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Phone &amp; Ext.Line.
        /// </summary>
        public static string IpPhoneExtLine {
            get {
                return ResourceManager.GetString("IpPhoneExtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDP.
        /// </summary>
        public static string Ldp {
            get {
                return ResourceManager.GetString("Ldp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahadasha.
        /// </summary>
        public static string Mahadasha {
            get {
                return ResourceManager.GetString("Mahadasha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        public static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Number.
        /// </summary>
        public static string NotificationNumber {
            get {
                return ResourceManager.GetString("NotificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Manual.
        /// </summary>
        public static string PoManual {
            get {
                return ResourceManager.GetString("PoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Scenario.
        /// </summary>
        public static string PredefinedScenario {
            get {
                return ResourceManager.GetString("PredefinedScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Number.
        /// </summary>
        public static string QuotationNumber {
            get {
                return ResourceManager.GetString("QuotationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Device.
        /// </summary>
        public static string ReturnDevice {
            get {
                return ResourceManager.GetString("ReturnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Number.
        /// </summary>
        public static string SalaryNumber {
            get {
                return ResourceManager.GetString("SalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Type.
        /// </summary>
        public static string ScenarioType {
            get {
                return ResourceManager.GetString("ScenarioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Delivery Date.
        /// </summary>
        public static string ServiceDeliveryDate {
            get {
                return ResourceManager.GetString("ServiceDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So Delivery Number.
        /// </summary>
        public static string SoDeliveryNumber {
            get {
                return ResourceManager.GetString("SoDeliveryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Type.
        /// </summary>
        public static string SoftwareType {
            get {
                return ResourceManager.GetString("SoftwareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Predefined Scenario.
        /// </summary>
        public static string SubPredefinedScenario {
            get {
                return ResourceManager.GetString("SubPredefinedScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination.
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo.
        /// </summary>
        public static string Trakindo {
            get {
                return ResourceManager.GetString("Trakindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Asset.
        /// </summary>
        public static string TransferAsset {
            get {
                return ResourceManager.GetString("TransferAsset", resourceCulture);
            }
        }
    }
}
