//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioBrokenResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioBrokenResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ScenarioBrokenResource", typeof(ScenarioBrokenResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupEquipmentNumber.
        /// </summary>
        internal static string BackupEquipmentNumber {
            get {
                return ResourceManager.GetString("BackupEquipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Equipment 1.
        /// </summary>
        internal static string BackupEquipmentNumber1 {
            get {
                return ResourceManager.GetString("BackupEquipmentNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Equipment 2.
        /// </summary>
        internal static string BackupEquipmentNumber2 {
            get {
                return ResourceManager.GetString("BackupEquipmentNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Equipment 3.
        /// </summary>
        internal static string BackupEquipmentNumber3 {
            get {
                return ResourceManager.GetString("BackupEquipmentNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo.
        /// </summary>
        internal static string Company1 {
            get {
                return ResourceManager.GetString("Company1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo2.
        /// </summary>
        internal static string Company2 {
            get {
                return ResourceManager.GetString("Company2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo3.
        /// </summary>
        internal static string Company3 {
            get {
                return ResourceManager.GetString("Company3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpdesk.
        /// </summary>
        internal static string Helpdesk {
            get {
                return ResourceManager.GetString("Helpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Date.
        /// </summary>
        internal static string NotificationDate {
            get {
                return ResourceManager.GetString("NotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification ID.
        /// </summary>
        internal static string NotificationId {
            get {
                return ResourceManager.GetString("NotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Admin.
        /// </summary>
        internal static string SalesAdmin {
            get {
                return ResourceManager.GetString("SalesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D6739.
        /// </summary>
        internal static string SnDevice1 {
            get {
                return ResourceManager.GetString("SnDevice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E6272.
        /// </summary>
        internal static string SnDevice2 {
            get {
                return ResourceManager.GetString("SnDevice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7382.
        /// </summary>
        internal static string SnDevice3 {
            get {
                return ResourceManager.GetString("SnDevice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN or ID Number.
        /// </summary>
        internal static string SnOrIdNumber {
            get {
                return ResourceManager.GetString("SnOrIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56473.
        /// </summary>
        internal static string SnOrIdNumber1 {
            get {
                return ResourceManager.GetString("SnOrIdNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72828.
        /// </summary>
        internal static string SnOrIdNumber2 {
            get {
                return ResourceManager.GetString("SnOrIdNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83929.
        /// </summary>
        internal static string SnOrIdNumber3 {
            get {
                return ResourceManager.GetString("SnOrIdNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G7383.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Holder Name.
        /// </summary>
        internal static string UserHolderName {
            get {
                return ResourceManager.GetString("UserHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendra Pratama.
        /// </summary>
        internal static string UserHolderName1 {
            get {
                return ResourceManager.GetString("UserHolderName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iis Dahlia.
        /// </summary>
        internal static string UserHolderName2 {
            get {
                return ResourceManager.GetString("UserHolderName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anang Hermansyah.
        /// </summary>
        internal static string UserHolderName3 {
            get {
                return ResourceManager.GetString("UserHolderName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Salary Number.
        /// </summary>
        internal static string UserSalaryNumber {
            get {
                return ResourceManager.GetString("UserSalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3647.
        /// </summary>
        internal static string UserSalaryNumber1 {
            get {
                return ResourceManager.GetString("UserSalaryNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8392.
        /// </summary>
        internal static string UserSalaryNumber2 {
            get {
                return ResourceManager.GetString("UserSalaryNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9382.
        /// </summary>
        internal static string UserSalaryNumber3 {
            get {
                return ResourceManager.GetString("UserSalaryNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
