//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScenarioReturnDeviceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Proformance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioReturnDeviceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ScenarioReturnDeviceResource", typeof(ScenarioReturnDeviceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo.
        /// </summary>
        public static string Company1 {
            get {
                return ResourceManager.GetString("Company1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MST.
        /// </summary>
        public static string Company2 {
            get {
                return ResourceManager.GetString("Company2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContractNumber1 {
            get {
                return ResourceManager.GetString("ContractNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Location.
        /// </summary>
        public static string NewLocation {
            get {
                return ResourceManager.GetString("NewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakarta.
        /// </summary>
        public static string NewLocation1 {
            get {
                return ResourceManager.GetString("NewLocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padang.
        /// </summary>
        public static string NewLocation2 {
            get {
                return ResourceManager.GetString("NewLocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palembang.
        /// </summary>
        public static string NewLocation3 {
            get {
                return ResourceManager.GetString("NewLocation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Delivery Number.
        /// </summary>
        public static string ReturnDeliveryNumber {
            get {
                return ResourceManager.GetString("ReturnDeliveryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7482.
        /// </summary>
        public static string ReturnDeliveryNumber1 {
            get {
                return ResourceManager.GetString("ReturnDeliveryNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9448.
        /// </summary>
        public static string ReturnDeliveryNumber2 {
            get {
                return ResourceManager.GetString("ReturnDeliveryNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8290.
        /// </summary>
        public static string ReturnDeliveryNumber3 {
            get {
                return ResourceManager.GetString("ReturnDeliveryNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8338.
        /// </summary>
        public static string SnOrIdNumber1 {
            get {
                return ResourceManager.GetString("SnOrIdNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7483.
        /// </summary>
        public static string SnOrIdNumber2 {
            get {
                return ResourceManager.GetString("SnOrIdNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8392.
        /// </summary>
        public static string SnOrIdNumber3 {
            get {
                return ResourceManager.GetString("SnOrIdNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Holder Name.
        /// </summary>
        public static string UserHolderName {
            get {
                return ResourceManager.GetString("UserHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendra Pratomo.
        /// </summary>
        public static string UserHolderName1 {
            get {
                return ResourceManager.GetString("UserHolderName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joko Widodo.
        /// </summary>
        public static string UserHolderName2 {
            get {
                return ResourceManager.GetString("UserHolderName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risma.
        /// </summary>
        public static string UserHolderName3 {
            get {
                return ResourceManager.GetString("UserHolderName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Salary Number.
        /// </summary>
        public static string UserSalaryNumber {
            get {
                return ResourceManager.GetString("UserSalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65744.
        /// </summary>
        public static string UserSalaryNumber1 {
            get {
                return ResourceManager.GetString("UserSalaryNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8239.
        /// </summary>
        public static string UserSalaryNumber2 {
            get {
                return ResourceManager.GetString("UserSalaryNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0292.
        /// </summary>
        public static string UserSalaryNumber3 {
            get {
                return ResourceManager.GetString("UserSalaryNumber3", resourceCulture);
            }
        }
    }
}
