//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScenarioTransferAssetsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioTransferAssetsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ScenarioTransferAssetsResource", typeof(ScenarioTransferAssetsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        public static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo.
        /// </summary>
        public static string Company1 {
            get {
                return ResourceManager.GetString("Company1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo2.
        /// </summary>
        public static string Company2 {
            get {
                return ResourceManager.GetString("Company2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo3.
        /// </summary>
        public static string Company3 {
            get {
                return ResourceManager.GetString("Company3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Line Number.
        /// </summary>
        public static string ContractLineNumber {
            get {
                return ResourceManager.GetString("ContractLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number 1.
        /// </summary>
        public static string CustomerNumber1 {
            get {
                return ResourceManager.GetString("CustomerNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custome rNumber 2.
        /// </summary>
        public static string CustomerNumber2 {
            get {
                return ResourceManager.GetString("CustomerNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number 3.
        /// </summary>
        public static string CustomerNumber3 {
            get {
                return ResourceManager.GetString("CustomerNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order To User.
        /// </summary>
        public static string DeliveryOrderToUser {
            get {
                return ResourceManager.GetString("DeliveryOrderToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Category.
        /// </summary>
        public static string DetailCategory {
            get {
                return ResourceManager.GetString("DetailCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Description.
        /// </summary>
        public static string EquipmentDescription {
            get {
                return ResourceManager.GetString("EquipmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCharges.
        /// </summary>
        public static string ErrorCharges {
            get {
                return ResourceManager.GetString("ErrorCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string Holder {
            get {
                return ResourceManager.GetString("Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idr Web Number.
        /// </summary>
        public static string IdrWebNumber {
            get {
                return ResourceManager.GetString("IdrWebNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        public static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract Line Number.
        /// </summary>
        public static string NewContractLineNumber {
            get {
                return ResourceManager.GetString("NewContractLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83493434.
        /// </summary>
        public static string NewContractNumbe1 {
            get {
                return ResourceManager.GetString("NewContractNumbe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34324324.
        /// </summary>
        public static string NewContractNumbe2 {
            get {
                return ResourceManager.GetString("NewContractNumbe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94023320.
        /// </summary>
        public static string NewContractNumbe3 {
            get {
                return ResourceManager.GetString("NewContractNumbe3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract Number.
        /// </summary>
        public static string NewContractNumber {
            get {
                return ResourceManager.GetString("NewContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Holder Name.
        /// </summary>
        public static string NewHolderName {
            get {
                return ResourceManager.GetString("NewHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pevita Pearce.
        /// </summary>
        public static string NewHolderName1 {
            get {
                return ResourceManager.GetString("NewHolderName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megan Fox.
        /// </summary>
        public static string NewHolderName2 {
            get {
                return ResourceManager.GetString("NewHolderName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cita Citata.
        /// </summary>
        public static string NewHolderName3 {
            get {
                return ResourceManager.GetString("NewHolderName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Location.
        /// </summary>
        public static string NewLocation {
            get {
                return ResourceManager.GetString("NewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pekanbaru.
        /// </summary>
        public static string NewLocation1 {
            get {
                return ResourceManager.GetString("NewLocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medan.
        /// </summary>
        public static string NewLocation2 {
            get {
                return ResourceManager.GetString("NewLocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padang.
        /// </summary>
        public static string NewLocation3 {
            get {
                return ResourceManager.GetString("NewLocation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Salary Number.
        /// </summary>
        public static string NewSalaryNumber {
            get {
                return ResourceManager.GetString("NewSalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3456.
        /// </summary>
        public static string NewSalaryNumber1 {
            get {
                return ResourceManager.GetString("NewSalaryNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4567.
        /// </summary>
        public static string NewSalaryNumber2 {
            get {
                return ResourceManager.GetString("NewSalaryNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5464.
        /// </summary>
        public static string NewSalaryNumber3 {
            get {
                return ResourceManager.GetString("NewSalaryNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scenario.
        /// </summary>
        public static string NewScenario {
            get {
                return ResourceManager.GetString("NewScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Holder Name.
        /// </summary>
        public static string OldHolderName {
            get {
                return ResourceManager.GetString("OldHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Location.
        /// </summary>
        public static string OldLocation {
            get {
                return ResourceManager.GetString("OldLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakarta.
        /// </summary>
        public static string OldLocation1 {
            get {
                return ResourceManager.GetString("OldLocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandung.
        /// </summary>
        public static string OldLocation2 {
            get {
                return ResourceManager.GetString("OldLocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bali.
        /// </summary>
        public static string OldLocation3 {
            get {
                return ResourceManager.GetString("OldLocation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Salary Number.
        /// </summary>
        public static string OldSalaryNumber {
            get {
                return ResourceManager.GetString("OldSalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Delivery Order.
        /// </summary>
        public static string ReturnDeliveryOrder {
            get {
                return ResourceManager.GetString("ReturnDeliveryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        public static string ReturnDeliveryOrder1 {
            get {
                return ResourceManager.GetString("ReturnDeliveryOrder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 124.
        /// </summary>
        public static string ReturnDeliveryOrder2 {
            get {
                return ResourceManager.GetString("ReturnDeliveryOrder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125.
        /// </summary>
        public static string ReturnDeliveryOrder3 {
            get {
                return ResourceManager.GetString("ReturnDeliveryOrder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Device.
        /// </summary>
        public static string ReturnDevice {
            get {
                return ResourceManager.GetString("ReturnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Creation Date.
        /// </summary>
        public static string RoutingCreationDate {
            get {
                return ResourceManager.GetString("RoutingCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Memo.
        /// </summary>
        public static string RoutingMemo {
            get {
                return ResourceManager.GetString("RoutingMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Type.
        /// </summary>
        public static string ScenarioType {
            get {
                return ResourceManager.GetString("ScenarioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sn Device.
        /// </summary>
        public static string SnDevice {
            get {
                return ResourceManager.GetString("SnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37284.
        /// </summary>
        public static string SnOrIdNumber1 {
            get {
                return ResourceManager.GetString("SnOrIdNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74893.
        /// </summary>
        public static string SnOrIdNumber2 {
            get {
                return ResourceManager.GetString("SnOrIdNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74833.
        /// </summary>
        public static string SnOrIdNumber3 {
            get {
                return ResourceManager.GetString("SnOrIdNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO Delivery Number.
        /// </summary>
        public static string SoDeliveryNumber {
            get {
                return ResourceManager.GetString("SoDeliveryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination.
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Category.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Asset.
        /// </summary>
        public static string TransferAsset {
            get {
                return ResourceManager.GetString("TransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Type.
        /// </summary>
        public static string TransferAssetType {
            get {
                return ResourceManager.GetString("TransferAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Holder Name.
        /// </summary>
        public static string UserHolderName {
            get {
                return ResourceManager.GetString("UserHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ali Utsman.
        /// </summary>
        public static string UserHolderName1 {
            get {
                return ResourceManager.GetString("UserHolderName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pevita Pearce yuli yuli yuli.
        /// </summary>
        public static string UserHolderName2 {
            get {
                return ResourceManager.GetString("UserHolderName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cita Citata.
        /// </summary>
        public static string UserHolderName3 {
            get {
                return ResourceManager.GetString("UserHolderName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Salary Number.
        /// </summary>
        public static string UserSalaryNumber {
            get {
                return ResourceManager.GetString("UserSalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93829292.
        /// </summary>
        public static string UserSalaryNumber1 {
            get {
                return ResourceManager.GetString("UserSalaryNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29110293.
        /// </summary>
        public static string UserSalaryNumber2 {
            get {
                return ResourceManager.GetString("UserSalaryNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29202013.
        /// </summary>
        public static string UserSalaryNumber3 {
            get {
                return ResourceManager.GetString("UserSalaryNumber3", resourceCulture);
            }
        }
    }
}
