//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceRequestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceRequestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.ServiceRequestResource", typeof(ServiceRequestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Blocked.
        /// </summary>
        public static string BillingBlocked {
            get {
                return ResourceManager.GetString("BillingBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion of Contract.
        /// </summary>
        public static string CompletionOfContract {
            get {
                return ResourceManager.GetString("CompletionOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ref. Automatic.
        /// </summary>
        public static string CreateRefAuto {
            get {
                return ResourceManager.GetString("CreateRefAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service Request.
        /// </summary>
        public static string CreateServiceRequest {
            get {
                return ResourceManager.GetString("CreateServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Rejection.
        /// </summary>
        public static string EquipmentRejection {
            get {
                return ResourceManager.GetString("EquipmentRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Service Request.
        /// </summary>
        public static string MaintainServiceRequest {
            get {
                return ResourceManager.GetString("MaintainServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification ID.
        /// </summary>
        public static string NotificationId {
            get {
                return ResourceManager.GetString("NotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string ReferenceId {
            get {
                return ResourceManager.GetString("ReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Reason.
        /// </summary>
        public static string TechnicalReason {
            get {
                return ResourceManager.GetString("TechnicalReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket ID.
        /// </summary>
        public static string TicketId {
            get {
                return ResourceManager.GetString("TicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        public static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
    }
}
