//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misi.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misi.MVC.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Completion Date.
        /// </summary>
        public static string ActualCompletionDate {
            get {
                return ResourceManager.GetString("ActualCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Routing.
        /// </summary>
        public static string AddRouting {
            get {
                return ResourceManager.GetString("AddRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Admin.
        /// </summary>
        public static string AssetAdmin {
            get {
                return ResourceManager.GetString("AssetAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Equipment Number.
        /// </summary>
        public static string BackupEquipmentNumber {
            get {
                return ResourceManager.GetString("BackupEquipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        public static string Baseline {
            get {
                return ResourceManager.GetString("Baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline Completion Date.
        /// </summary>
        public static string BaselineCompletionDate {
            get {
                return ResourceManager.GetString("BaselineCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing System.
        /// </summary>
        public static string BillingSystem {
            get {
                return ResourceManager.GetString("BillingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking Status.
        /// </summary>
        public static string BlockingStatus {
            get {
                return ResourceManager.GetString("BlockingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        public static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrac Line Number.
        /// </summary>
        public static string ContracLineNumber {
            get {
                return ResourceManager.GetString("ContracLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End.
        /// </summary>
        public static string ContractEnd {
            get {
                return ResourceManager.GetString("ContractEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Item.
        /// </summary>
        public static string ContractItem {
            get {
                return ResourceManager.GetString("ContractItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Line Number.
        /// </summary>
        public static string ContractLineNumber {
            get {
                return ResourceManager.GetString("ContractLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start.
        /// </summary>
        public static string ContractStart {
            get {
                return ResourceManager.GetString("ContractStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create with Reference.
        /// </summary>
        public static string CreateRef {
            get {
                return ResourceManager.GetString("CreateRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service Request.
        /// </summary>
        public static string CreateServiceRequest {
            get {
                return ResourceManager.GetString("CreateServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Admin.
        /// </summary>
        public static string DeliveryAdmin {
            get {
                return ResourceManager.GetString("DeliveryAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekstop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Description.
        /// </summary>
        public static string DeviceDescription {
            get {
                return ResourceManager.GetString("DeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Status.
        /// </summary>
        public static string DivisionStatus {
            get {
                return ResourceManager.GetString("DivisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Description.
        /// </summary>
        public static string EquipmentDescription {
            get {
                return ResourceManager.GetString("EquipmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Charges.
        /// </summary>
        public static string ErrorCharges {
            get {
                return ResourceManager.GetString("ErrorCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpdesk.
        /// </summary>
        public static string Helpdesk {
            get {
                return ResourceManager.GetString("Helpdesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Name.
        /// </summary>
        public static string HolderName {
            get {
                return ResourceManager.GetString("HolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Name Details.
        /// </summary>
        public static string HolderNameDetails {
            get {
                return ResourceManager.GetString("HolderNameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR Web Number.
        /// </summary>
        public static string IdrWebNumber {
            get {
                return ResourceManager.GetString("IdrWebNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Phone.
        /// </summary>
        public static string IpPhone {
            get {
                return ResourceManager.GetString("IpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Date.
        /// </summary>
        public static string IssuedDate {
            get {
                return ResourceManager.GetString("IssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued ID.
        /// </summary>
        public static string IssuedId {
            get {
                return ResourceManager.GetString("IssuedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        public static string ItemCategory {
            get {
                return ResourceManager.GetString("ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop.
        /// </summary>
        public static string Laptop {
            get {
                return ResourceManager.GetString("Laptop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogMessage.
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain.
        /// </summary>
        public static string Maintain {
            get {
                return ResourceManager.GetString("Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Description.
        /// </summary>
        public static string MaterialDescription {
            get {
                return ResourceManager.GetString("MaterialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Pricing.
        /// </summary>
        public static string MaterialPricing {
            get {
                return ResourceManager.GetString("MaterialPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MST.
        /// </summary>
        public static string Mst {
            get {
                return ResourceManager.GetString("Mst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        public static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract Line Number.
        /// </summary>
        public static string NewContractLineNumber {
            get {
                return ResourceManager.GetString("NewContractLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Location.
        /// </summary>
        public static string NewLocation {
            get {
                return ResourceManager.GetString("NewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scenario Name .
        /// </summary>
        public static string NewNameScenario {
            get {
                return ResourceManager.GetString("NewNameScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scenario.
        /// </summary>
        public static string NewScenario {
            get {
                return ResourceManager.GetString("NewScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Date.
        /// </summary>
        public static string NotificationDate {
            get {
                return ResourceManager.GetString("NotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification ID.
        /// </summary>
        public static string NotificationId {
            get {
                return ResourceManager.GetString("NotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT READY.
        /// </summary>
        public static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Completion Date.
        /// </summary>
        public static string PlanCompletionDate {
            get {
                return ResourceManager.GetString("PlanCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Number.
        /// </summary>
        public static string PoNumber {
            get {
                return ResourceManager.GetString("PoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Scenario.
        /// </summary>
        public static string PredefinedScenario {
            get {
                return ResourceManager.GetString("PredefinedScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Scenario .
        /// </summary>
        public static string PredefinedScenarioList {
            get {
                return ResourceManager.GetString("PredefinedScenarioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Service Request.
        /// </summary>
        public static string PreviewServiceRequest {
            get {
                return ResourceManager.GetString("PreviewServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Group.
        /// </summary>
        public static string PriceGroup {
            get {
                return ResourceManager.GetString("PriceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Rejection.
        /// </summary>
        public static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected by Division.
        /// </summary>
        public static string RejectedByDivision {
            get {
                return ResourceManager.GetString("RejectedByDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected by SA.
        /// </summary>
        public static string RejectedBySa {
            get {
                return ResourceManager.GetString("RejectedBySa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        public static string RequestedBy {
            get {
                return ResourceManager.GetString("RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Via.
        /// </summary>
        public static string RequestedVia {
            get {
                return ResourceManager.GetString("RequestedVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request For Adjustment.
        /// </summary>
        public static string RequestForAdjustment {
            get {
                return ResourceManager.GetString("RequestForAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Information.
        /// </summary>
        public static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Memo.
        /// </summary>
        public static string RequestMemo {
            get {
                return ResourceManager.GetString("RequestMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Via.
        /// </summary>
        public static string RequestVia {
            get {
                return ResourceManager.GetString("RequestVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Device.
        /// </summary>
        public static string ReturnDevice {
            get {
                return ResourceManager.GetString("ReturnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Creating Date.
        /// </summary>
        public static string RoutingCreatingDate {
            get {
                return ResourceManager.GetString("RoutingCreatingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Creation Date.
        /// </summary>
        public static string RoutingCreationDate {
            get {
                return ResourceManager.GetString("RoutingCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Information.
        /// </summary>
        public static string RoutingInfo {
            get {
                return ResourceManager.GetString("RoutingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Memo.
        /// </summary>
        public static string RoutingMemo {
            get {
                return ResourceManager.GetString("RoutingMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Status.
        /// </summary>
        public static string RoutingStatus {
            get {
                return ResourceManager.GetString("RoutingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Status List.
        /// </summary>
        public static string RoutingStatusList {
            get {
                return ResourceManager.GetString("RoutingStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Table.
        /// </summary>
        public static string RoutingTable {
            get {
                return ResourceManager.GetString("RoutingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Creation Date.
        /// </summary>
        public static string RutingCreationDate {
            get {
                return ResourceManager.GetString("RutingCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Admin.
        /// </summary>
        public static string SalesAdmin {
            get {
                return ResourceManager.GetString("SalesAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP System.
        /// </summary>
        public static string SapSystem {
            get {
                return ResourceManager.GetString("SapSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Status.
        /// </summary>
        public static string SaStatus {
            get {
                return ResourceManager.GetString("SaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Draft.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Attribute.
        /// </summary>
        public static string ScenarioAttribute {
            get {
                return ResourceManager.GetString("ScenarioAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Charges.
        /// </summary>
        public static string ScenarioErrorCharges {
            get {
                return ResourceManager.GetString("ScenarioErrorCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario New.
        /// </summary>
        public static string ScenarioNew {
            get {
                return ResourceManager.GetString("ScenarioNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        public static string ScenarioNewContract {
            get {
                return ResourceManager.GetString("ScenarioNewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Device.
        /// </summary>
        public static string ScenarioReturnDevice {
            get {
                return ResourceManager.GetString("ScenarioReturnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Termination.
        /// </summary>
        public static string ScenarioTermination {
            get {
                return ResourceManager.GetString("ScenarioTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Asset.
        /// </summary>
        public static string ScenarioTransferAsset {
            get {
                return ResourceManager.GetString("ScenarioTransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM-Delivery.
        /// </summary>
        public static string ScmDelivery {
            get {
                return ResourceManager.GetString("ScmDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM-Warehouse.
        /// </summary>
        public static string ScmWarehouse {
            get {
                return ResourceManager.GetString("ScmWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM-Warehouse Admin.
        /// </summary>
        public static string ScmWarehouseAdmin {
            get {
                return ResourceManager.GetString("ScmWarehouseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID.
        /// </summary>
        public static string ServiceId {
            get {
                return ResourceManager.GetString("ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        public static string ServiceRequest {
            get {
                return ResourceManager.GetString("ServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N Device.
        /// </summary>
        public static string SnDevice {
            get {
                return ResourceManager.GetString("SnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN or ID Number.
        /// </summary>
        public static string SnOrIdNumber {
            get {
                return ResourceManager.GetString("SnOrIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO Contract Number.
        /// </summary>
        public static string SoContractNumber {
            get {
                return ResourceManager.GetString("SoContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold To Party.
        /// </summary>
        public static string SoldToParty {
            get {
                return ResourceManager.GetString("SoldToParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        public static string SpaceChar {
            get {
                return ResourceManager.GetString("SpaceChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitech.
        /// </summary>
        public static string Stiech {
            get {
                return ResourceManager.GetString("Stiech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestInfoHeadingViewModel.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Support.
        /// </summary>
        public static string SystemSupport {
            get {
                return ResourceManager.GetString("SystemSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Qty.
        /// </summary>
        public static string TargetQty {
            get {
                return ResourceManager.GetString("TargetQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination.
        /// </summary>
        public static string Termination {
            get {
                return ResourceManager.GetString("Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin Client.
        /// </summary>
        public static string ThinClient {
            get {
                return ResourceManager.GetString("ThinClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Category.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket ID.
        /// </summary>
        public static string TicketId {
            get {
                return ResourceManager.GetString("TicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakindo.
        /// </summary>
        public static string Trakindo {
            get {
                return ResourceManager.GetString("Trakindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Asset.
        /// </summary>
        public static string TransferAsset {
            get {
                return ResourceManager.GetString("TransferAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Assets.
        /// </summary>
        public static string TransferAssets {
            get {
                return ResourceManager.GetString("TransferAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Asset Type.
        /// </summary>
        public static string TransferAssetType {
            get {
                return ResourceManager.GetString("TransferAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trhin Client.
        /// </summary>
        public static string TrhinClient {
            get {
                return ResourceManager.GetString("TrhinClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblocked.
        /// </summary>
        public static string UnBlocked {
            get {
                return ResourceManager.GetString("UnBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Holder Name.
        /// </summary>
        public static string UserHolderName {
            get {
                return ResourceManager.GetString("UserHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Salary Number.
        /// </summary>
        public static string UserSalaryNumber {
            get {
                return ResourceManager.GetString("UserSalaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Admin.
        /// </summary>
        public static string WarehouseAdmin {
            get {
                return ResourceManager.GetString("WarehouseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBS Element.
        /// </summary>
        public static string WbsElement {
            get {
                return ResourceManager.GetString("WbsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISI - Billing Statement.
        /// </summary>
        public static string WebSiteTitle {
            get {
                return ResourceManager.GetString("WebSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Approval.
        /// </summary>
        public static string WorkflowApproval {
            get {
                return ResourceManager.GetString("WorkflowApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Admin.
        /// </summary>
        public static string WorkshopAdmin {
            get {
                return ResourceManager.GetString("WorkshopAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
